version: "3"
services:
  bot:
    container_name: nevermind_ow
    build:
      context: .
      dockerfile: Dockerfile
    logging:
      driver: "json-file"

  lavalink:
    container_name: lavalink
    image: fredboat/lavalink:master
    restart: always
    ports:
      - "2333:2333"
    volumes:
      - ./Lavalink/application.yml:/opt/Lavalink/application.yml
    logging:
      driver: "json-file"
